# Generated by Django 4.2.30 on 2026-06-20 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'channel_partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('score_updated', 'Health Score Updated (>2 point change)'), ('anomaly_flagged', 'Anomaly Flagged by ML Engine')], max_length=50)),
                ('secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='api_management.channelpartner')),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api_management.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key_secret_hash', models.CharField(max_length=255)),
                ('label', models.CharField(default='Default Key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api_management.channelpartner')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('request_size_bytes', models.IntegerField(default=0)),
                ('response_size_bytes', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='api_management.apikey')),
            ],
            options={
                'db_table': 'api_usage_logs',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['api_key', 'requested_at'], name='api_usage_l_api_key_fc793a_idx'), models.Index(fields=['endpoint', 'requested_at'], name='api_usage_l_endpoin_87c5b5_idx')],
            },
        ),
    ]
