# Generated by Django 4.2.30 on 2026-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCompany',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('nse_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bse_url', models.CharField(blank=True, max_length=500, null=True)),
                ('face_value', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('roce_percentage', models.FloatField(blank=True, db_column='roce_pct', null=True)),
                ('roe_percentage', models.FloatField(blank=True, db_column='roe_pct', null=True)),
            ],
            options={
                'db_table': 'dim_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimHealthLabel',
            fields=[
                ('label_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('color_hex', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dim_health_label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSector',
            fields=[
                ('sector_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100)),
                ('sector_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dim_sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimYear',
            fields=[
                ('year_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year_label', models.CharField(max_length=20)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.CharField(blank=True, max_length=5, null=True)),
                ('is_ttm', models.BooleanField(default=False)),
                ('is_half_year', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_year',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('period_label', models.CharField(max_length=10)),
                ('compounded_sales_growth_pct', models.FloatField(blank=True, null=True)),
                ('compounded_profit_growth_pct', models.FloatField(blank=True, null=True)),
                ('stock_price_cagr_pct', models.FloatField(blank=True, null=True)),
                ('roe_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactAnomaly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('metric', models.CharField(blank=True, max_length=100, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_method', models.CharField(blank=True, max_length=30, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_anomalies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactBalanceSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('equity_capital', models.FloatField(blank=True, null=True)),
                ('reserves', models.FloatField(blank=True, null=True)),
                ('borrowings', models.FloatField(blank=True, null=True)),
                ('other_liabilities', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.FloatField(blank=True, null=True)),
                ('fixed_assets', models.FloatField(blank=True, null=True)),
                ('cwip', models.FloatField(blank=True, null=True)),
                ('investments', models.FloatField(blank=True, null=True)),
                ('other_assets', models.FloatField(blank=True, db_column='other_asset', null=True)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_balance_sheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCashFlow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('operating_activity', models.FloatField(blank=True, null=True)),
                ('investing_activity', models.FloatField(blank=True, null=True)),
                ('financing_activity', models.FloatField(blank=True, null=True)),
                ('net_cash_flow', models.FloatField(blank=True, null=True)),
                ('free_cash_flow', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_cash_flow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactCluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('cluster_label', models.CharField(blank=True, max_length=200, null=True)),
                ('pca_x', models.FloatField(blank=True, null=True)),
                ('pca_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_clusters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('annual_report', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'fact_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactMLScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('profitability_score', models.FloatField(blank=True, null=True)),
                ('growth_score', models.FloatField(blank=True, null=True)),
                ('leverage_score', models.FloatField(blank=True, null=True)),
                ('cashflow_score', models.FloatField(blank=True, null=True)),
                ('dividend_score', models.FloatField(blank=True, null=True)),
                ('trend_score', models.FloatField(blank=True, null=True)),
                ('health_label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProfitLoss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('expenses', models.FloatField(blank=True, null=True)),
                ('operating_profit', models.FloatField(blank=True, null=True)),
                ('opm_pct', models.FloatField(blank=True, null=True)),
                ('other_income', models.FloatField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
                ('depreciation', models.FloatField(blank=True, null=True)),
                ('profit_before_tax', models.FloatField(blank=True, null=True)),
                ('tax_pct', models.FloatField(blank=True, null=True)),
                ('net_profit', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_payout', models.FloatField(blank=True, null=True)),
                ('net_profit_margin_pct', models.FloatField(blank=True, null=True)),
                ('expense_ratio_pct', models.FloatField(blank=True, null=True)),
                ('interest_coverage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_profit_loss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactProsCons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('is_pro', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_pros_cons',
                'managed': False,
            },
        ),
    ]
